### ISSUE TITLE
[feature request]: Make task execution not depend on the extension

### ISSUE THREAD

**Issue by aajtodd** [smithy-lang/smithy-gradle-plugin#45]
It would be nice if the tasks provided by this plugin didn't require the `smithy` extension/plugin to be installed. 

I would like to re-use the `SmithyBuild` task but doing so [requires](https://github.com/awslabs/smithy-gradle-plugin/blob/main/src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuild.java#L90) that the plugin be installed so that the extension exists. This isn't the only place, there is a lot of implicit use of the extension in the utils called elsewhere. 

Tasks in general should probably be extension agnostic. When the plugin registers tasks it should set the appropriate task input from the extension alleviating the need for the task itself to know about the extension. 

Most of the SDKs building off smithy gradle plugin aren't using the default functionality provided by this plugin, only the `SmithyBuild` task with a custom `smithy-build.json`

* [Go v2](https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/sdk-codegen/build.gradle.kts#L44)
* [JS v3](https://github.com/aws/aws-sdk-js-v3/blob/main/codegen/sdk-codegen/build.gradle.kts#L48)
* [Kotlin](https://github.com/awslabs/aws-sdk-kotlin/blob/main/codegen/sdk/build.gradle.kts#L308)
* [Swift](https://github.com/awslabs/aws-sdk-swift/blob/main/codegen/sdk-codegen/build.gradle.kts#L29)

The plugin also applies the `java` plugin which isn't necessarily desirable for our use case either. It would be nice if the plugin only took actions when the java plugin is present rather than applying it.

**Comment by aajtodd** [comment]
One of the reasons we don't necessarily want the `java` plugin applied for us by default: https://github.com/awslabs/aws-sdk-kotlin/pull/496

Similar to what I was saying about extensions, it would be nice if the plugin didn't rely on the `java` plugin and instead query if it exists and register it's behavior tied to that plugin only if it is applied already.

**Comment by rschmitt** [comment]
I think the way this is often approached idiomatically is by splitting the plugin into two plugins, a "base" plugin that defines tasks and common data types, and a high-level plugin that applies conventions, installs extensions, etc. The reason you still want to model the former as a plugin is so that it can be applied through the `plugins` DSL block, which removes the need to manually tamper with the script's classpath in the `buildscript` block.

**Comment by hpmellema** [comment]
Release 0.8.0 has refactored the plugin into base and jar plugins and has also removed the call to apply the java plugin.
