### ISSUE TITLE
Add support for configuration caching

### ISSUE THREAD

**Issue by rschmitt** [smithy-lang/smithy-gradle-plugin#56]
The Smithy tasks refer to `Task.project` at execution time, which [breaks configuration caching](https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution).

**Comment by rschmitt** [comment]
I'm referring to the Smithy Gradle plugin itself, not its build process. All three tasks (`smithyTags`, `smithyBuildJar`, and `smithyValidate`) invoke `getProject()` at execution time, which breaks configuration caching in any builds that use the Smithy Gradle plugin.

**Comment by hpmellema** [comment]
Support for configuration caching (and removal of calls to getProject() at execution time) has been addressed in release 0.8.0.
An integration test has also been added to verify configuration caching works for the jar plugin:  https://github.com/smithy-lang/smithy-gradle-plugin/blob/main/smithy-jar-plugin/src/it/java/software/amazon/smithy/gradle/SourceProjectionTest.java#L36
