### ISSUE TITLE
`SmithyExtension` options are not correctly modeled as task inputs

### ISSUE THREAD

**Issue by rschmitt** [smithy-lang/smithy-gradle-plugin#72]
The `SmithyBuildJar` task runs the following code at execution time (i.e. in `SmithyBuildJar::execute`):

```java
        // Merge or overwrite?
        if (smithyBuildConfigs == null) {
            setSmithyBuildConfigs(extension.getSmithyBuildConfigs());
            getLogger().debug("Setting SmithyBuildJar smithyBuildConfigs from extension: {}", smithyBuildConfigs);
        }
```

This is effectively an unmodeled task input and is therefore incorrect. It can cause Gradle to skip this task entirely, or to fail to evaluate a lazy file collection provided to the extension as an input. To fix this,  you either have to share the same `FileCollection` instance between `SmithyExtension` and `SmithyBuildJar`, or you have to return both instances as `@InputFiles` from `SmithyBuildJar`.

**Comment by brandondahler** [comment]
Encountered a situation where this specifically impacted me, was able to work around it via:

```
tasks {
  smithyBuildJar {
    smithyBuildConfigs = smithy.smithyBuildConfigs
  }
}
```

**Comment by hpmellema** [comment]
Task inputs have been updated in the 0.8.0 release to correctly model task inputs.
If you find there are still issues when testing out this new release please feel free to re-open this ticket.
